import 'dart:convert';
import 'dart:io';

const _groundTruthPaths = [
  'assets/benchmark/phase6a/whatsapp_style.json',
  'assets/benchmark/phase6a/tinder_style.json',
  'assets/benchmark/phase6a/bumble_style.json',
  'assets/benchmark/phase6a/hinge_style.json',
  'assets/benchmark/phase6a/instagram_dm_style.json',
  'assets/benchmark/phase6a/event_timeline_style.json',
  'assets/benchmark/phase6a/reaction_lab_style.json',
];

const _outputPath = 'benchmark/phase6a/generated_fixture_catalog.dart';

Future<void> main() async {
  final output = StringBuffer()
    ..writeln('// Generated by tool/generate_phase6a_fixture_catalog.dart.')
    ..writeln('// Do not edit this file directly.')
    ..writeln()
    ..writeln('const phase6aEmbeddedGroundTruth = <String, String>{');
  const encoder = JsonEncoder.withIndent('  ');
  for (final path in _groundTruthPaths) {
    final source = await File(path).readAsString();
    final decoded = jsonDecode(source);
    final normalized = encoder.convert(decoded);
    if (normalized.contains("'''")) {
      throw FormatException('Ground truth $path contains an unsafe delimiter.');
    }
    output
      ..writeln("  '$path': r'''$normalized''',")
      ..writeln();
  }
  output.writeln('};');
  await File(_outputPath).writeAsString(output.toString(), flush: true);
  stdout.writeln('Generated ${_groundTruthPaths.length} Phase 6A fixtures.');
}
