"""Content-free Phase 11 Conversation Coach API transport contracts."""

from datetime import datetime
from enum import StrEnum
from typing import Annotated, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, StringConstraints, model_validator


class CoachPreviewErrorCode(StrEnum):
    """Stable client-safe failure vocabulary."""

    FEATURE_DISABLED = "feature_disabled"
    MOCK_DISABLED = "mock_disabled"
    AUTHENTICATION_REQUIRED = "authentication_required"
    AUTHORIZATION_FAILED = "authorization_failed"
    CONSENT_REQUIRED = "consent_required"
    EXTERNAL_PROCESSING_CONSENT_REQUIRED = "external_processing_consent_required"
    CONVERSATION_UNAVAILABLE = "conversation_unavailable"
    REVIEW_INCOMPLETE = "review_incomplete"
    SCHEMA_UNSUPPORTED = "schema_unsupported"
    INCOMPLETE_TIMELINE = "incomplete_timeline"
    SAFETY_REJECTED = "safety_rejected"
    CANCELLED = "cancelled"
    TIMED_OUT = "timed_out"
    PROVIDER_UNAVAILABLE = "provider_unavailable"
    RESPONSE_VALIDATION_FAILED = "response_validation_failed"
    CAPABILITY_UNSUPPORTED = "capability_unsupported"
    IDEMPOTENCY_REQUIRED = "idempotency_required"
    IDEMPOTENCY_CONFLICT = "idempotency_conflict"
    IDEMPOTENCY_IN_PROGRESS = "idempotency_in_progress"
    IDEMPOTENCY_REPLAYED = "idempotency_replayed"
    ALLOWANCE_EXHAUSTED = "allowance_exhausted"
    RATE_LIMITED = "rate_limited"
    BUDGET_EXHAUSTED = "budget_exhausted"
    USAGE_UNAVAILABLE = "usage_unavailable"
    INTERNAL_SAFE_FAILURE = "internal_safe_failure"


class CoachPreviewSectionTransportV1(BaseModel):
    """One renderer-owned section containing only keys and structural counts."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    schema_version: Literal["conversation-coach-preview-section.v1"] = (
        "conversation-coach-preview-section.v1"
    )
    identifier: str
    heading_localization_key: str
    semantic_label_localization_key: str
    status: Literal["available", "unavailable", "notice"]
    item_localization_keys: tuple[str, ...]
    evidence_reference_count: int


class CoachPreviewCalculationVersionsV1(BaseModel):
    """Version facts required for strict client compatibility."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    analytics_schema_version: Literal["conversation-analytics.v1"] = "conversation-analytics.v1"
    analytics_calculation_version: Literal["deterministic-conversation-analytics.v1"] = (
        "deterministic-conversation-analytics.v1"
    )
    source_event_schema_version: Literal["conversation-events.v1"] = "conversation-events.v1"


class CoachPreviewProvenanceV1(BaseModel):
    """Content-free execution provenance; never provider payload or evidence."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    provider_identifier: Literal["mock-ai-provider.v1"] = "mock-ai-provider.v1"
    generator_identifier: Literal["deterministic-coaching-response-mock.v1"] = (
        "deterministic-coaching-response-mock.v1"
    )
    mock_execution: Literal[True] = True


class CoachPreviewSuccessV1(BaseModel):
    """Exact-key immutable success response for the mock-only preview."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    schema_version: Literal["conversation-coach-preview.v1"] = "conversation-coach-preview.v1"
    execution_status: Literal["completed"] = "completed"
    response_schema_version: Literal["ai-coaching-response.v1"] = "ai-coaching-response.v1"
    renderer_schema_version: Literal["ai-coaching-renderer-projection.v1"] = (
        "ai-coaching-renderer-projection.v1"
    )
    response_id: UUID
    locale: str
    calculation_versions: CoachPreviewCalculationVersionsV1
    sections: tuple[CoachPreviewSectionTransportV1, ...]
    notices: tuple[str, ...]
    provenance: CoachPreviewProvenanceV1
    correlation_id: UUID


class CoachPreviewErrorV1(BaseModel):
    """Stable localized error information without diagnostics or raw exceptions."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    error_id: str
    code: CoachPreviewErrorCode
    localization_key: str
    retryable: bool
    retry_guidance_localization_key: str | None
    correlation_id: UUID


class CoachPreviewFailureV1(BaseModel):
    """Exact-key immutable failure envelope."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    schema_version: Literal["conversation-coach-preview-error.v1"] = (
        "conversation-coach-preview-error.v1"
    )
    error: CoachPreviewErrorV1


class CoachLiveObservationV1(BaseModel):
    """Evidence-linked, contestable observation generated by an approved model."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    heading: str
    observation: str
    uncertainty: str
    alternative_interpretations: tuple[str, ...]
    evidence_event_ids: tuple[UUID, ...]


class CoachLiveReplyDraftV1(BaseModel):
    """A draft the user may review and edit; never an auto-send instruction."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    text: str
    tone: str
    rationale: str


class CoachLiveProvenanceV1(BaseModel):
    """Public provider facts without response IDs, prompts, or private content."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    provider_identifier: Literal[
        "openai-responses-gpt-5.6-terra.v1",
        "zai-chat-completions-glm-5.2.v1",
        "openrouter-chat-completions-tiered.v1",
    ] = "openai-responses-gpt-5.6-terra.v1"
    model: Annotated[
        str,
        StringConstraints(
            min_length=1,
            max_length=96,
            pattern=r"^(?:gpt-5\.6-terra|glm-5\.2|[A-Za-z0-9._~:-]+/[A-Za-z0-9._~:-]+)$",
        ),
    ] = "gpt-5.6-terra"
    mock_execution: Literal[False] = False
    response_stored_by_application: Literal[False] = False


class CoachLiveUsageV1(BaseModel):
    """Content-free token counts for transparent cost measurement."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    input_tokens: int
    output_tokens: int
    total_tokens: int


class CoachLiveAllowanceV1(BaseModel):
    """Server-owned allowance state after the completed billable action."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    schema_version: Literal["coach-allowance.v1"] = "coach-allowance.v1"
    server_version: Literal["subscription-runtime.v1"] = "subscription-runtime.v1"
    plan_code: Literal["welcome", "free", "plus"]
    plan_status: Literal["active", "grace"]
    allowance_kind: Literal["conversation_analysis"] = "conversation_analysis"
    limit: int
    consumed: int
    reserved: int
    remaining: int
    reset_at: datetime


class CoachLiveSuccessV2(BaseModel):
    """Validated coaching response with server-owned usage accounting."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    schema_version: Literal["conversation-coach.v2"] = "conversation-coach.v2"
    execution_status: Literal["completed"] = "completed"
    response_schema_version: Literal[
        "terra-coach-output.v1",
        "glm-coach-output.v1",
        "openrouter-coach-output.v1",
    ] = "terra-coach-output.v1"
    response_id: UUID
    locale: Literal["en"] = "en"
    summary: str
    observations: tuple[CoachLiveObservationV1, ...]
    next_steps: tuple[str, ...]
    reply_drafts: tuple[CoachLiveReplyDraftV1, ...]
    safety_notices: tuple[str, ...]
    limitations: tuple[str, ...]
    provenance: CoachLiveProvenanceV1
    usage: CoachLiveUsageV1
    allowance: CoachLiveAllowanceV1
    correlation_id: UUID

    @model_validator(mode="after")
    def provenance_matches_response_schema(self) -> "CoachLiveSuccessV2":
        triple = (
            self.response_schema_version,
            self.provenance.provider_identifier,
            self.provenance.model,
        )
        if triple in {
            (
                "terra-coach-output.v1",
                "openai-responses-gpt-5.6-terra.v1",
                "gpt-5.6-terra",
            ),
            (
                "glm-coach-output.v1",
                "zai-chat-completions-glm-5.2.v1",
                "glm-5.2",
            ),
        }:
            return self
        if (
            self.response_schema_version == "openrouter-coach-output.v1"
            and self.provenance.provider_identifier == "openrouter-chat-completions-tiered.v1"
            and "/" in self.provenance.model
        ):
            return self
        raise ValueError("live_coach_provenance_mismatch")
